### ISSUE TITLE
Implement GroupMessage as interface

### ISSUE THREAD

**Issue by delvh** [informatik-ag-ngl/envoy-common#26]
in the current state, `GroupMessage` is implemented as a class extending `Message`.
This is however not a viable solution as over time the amount of messages that can be send will increase (Voice, image, attachment, (forwarded), ... message). If we were to implement a separate `GroupMessage` for every subclass, the readability of Envoy would greatly decrease ( + no one would want to implement all that).

**Comment by CyB3RC0nN0R** [comment]
I think I found a sensible way of dealing with attachments without messing up the inheritance hierarchy (see #29), so for now this is unnecessary.

My reasoning behind this is that an attachment is basically a file transported as part of a message, so its actual data can be represented using a `byte[]`. To denote the type of the attachment, a simple `enum` would also suffice, eliminating problems caused be generics and inheritance hierarchies.
